[package]
name = "party"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
bincode = "1"
dirs = "6"

[dev-dependencies]
tempfile = "3"
