[package]
name = "post-push-party"
version = "0.1.0"
authors = ["Drew Dele√≥n-Zemke"]
edition = "2021"
license = "GPL-3.0"
description = "Celebrate your git pushes!"
repository = "https://github.com/drewzemke/post-push-party"

[[bin]]
name = "party"
path = "src/main.rs"

[dependencies]
bincode = "1"
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
crossterm = "0.28"
dirs = "6"
rand = "0.9"
ratatui = "0.30"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tui-scrollview = "0.6"

[dev-dependencies]
tempfile = "3"

[features]
dev = []
