[package]
name = "party"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
bincode = "1"
dirs = "6"
rand = "0.9"
ratatui = "0.30"
crossterm = "0.28"
tui-scrollview = "0.6"
chrono = "0.4"

[dev-dependencies]
tempfile = "3"

[features]
dev = []
